### ISSUE TITLE
Missing attribution to OSM

### ISSUE THREAD

**Issue by matthewdarwin** [BikeOttawa/maps.bikeottawa.ca-frontend#11]
There is no attribution on any of our maps.  It needs to be (C) OSM Contributors

**Comment by zzptichka** [comment]
Huh. I'm 100% sure it used to be there. Probably something changed on mapbox side. Will have a look later.

**Comment by zzptichka** [comment]
Fixed

**Comment by matthewdarwin** [comment]
Still doesn't seem solved in all maps, from what i see.

**Comment by zzptichka** [comment]
Should be good now.

**Comment by matthewdarwin** [comment]
Different maps work differently (either (i) button, or shown always) but yes, attribution is there.
