### ISSUE TITLE
sensitivity: selecting a way

### ISSUE THREAD

**Issue by heatshear** [BikeOttawa/maps.bikeottawa.ca-frontend#13]
Using an iPad (or any touchscreen?) it's hard to put a finger on exactly the right spot to select a way. Can the sensitive zone be made wider, especially if zoomed in? Otherwise, works great to select/edit tags/deselect.

**Comment by zzptichka** [comment]
Fixed in https://github.com/BikeOttawa/maps.bikeottawa.ca-frontend/commit/dca168d154f7825691562d1769b62e97e2f0c9c9
Lines should be much thicker at higher zoom levels now  - 10px now vs 2px before
