### ISSUE TITLE
winter map: fixme box, other points of clarification

### ISSUE THREAD

**Issue by heatshear** [BikeOttawa/maps.bikeottawa.ca-frontend#14]
I had my beta tester try this map. He has no idea about mapping. He found the main features to be intuitive, except for "fixme", which he didn't understand. I suggested "comments (optional)" and he interpreted that to mean that he should explain why he tagged the path the way he did. "Other edits needed"/"Suggestions" is more intuitive to him, though "suggestions" might earn us some suggestions about how things should be fixed irl (he was wondering if that's how it would work), but I can live with that.

Other comments from the non-mapper: 

1) Why is there a name field and no name? (the case for most paths). Should I name it? (So we could delete that field.) 

2) Why is this path called a highway, that seems wrong? (I agree - we don't need to show this to everyone - it will probably just sow confusion)

3) Width should have a unit of measure: Width (m). Even then, he's too scared to guess at how wide he should label a path to be. Says he probably wouldn't do it. Some guidance on that may be good. Don't know if we can provide it in the map, but I will at least add it to a blog post.

**Comment by zzptichka** [comment]
- I added hints, so that would help I guess. "Suggestions" definitely sounds like something you want to tell the city, not map maintainers... Maybe "other info"?  
- Empty names removed
- Let me see what I can do about highway
- Added 'm'. In the blog post mention that most pathways range between 1m (narrow footways between houses) and 3m (SJAM pathway). Being wrong by +/-0.5m doesn't play a big role.

**Comment by zzptichka** [comment]
Renamed tag names in https://github.com/BikeOttawa/maps.bikeottawa.ca-frontend/commit/4c4908f7cca130cb91959e517c1671a274ae95a5 
Currently according to this table:
```['name','Name'],        //[actual OSM tag, display name for tag in popup]
                          ['highway','Type'],
                          ['winter_service','Snowplowing'],
                          ['width', 'Width'],
                          ['surface', 'Surface'],
                          ['smoothness', 'Smoothness'],
                          ['fixme', 'Other info']
```
If you can think of better names let me know.

**Comment by heatshear** [comment]
I like that - I think you've done a great job of making this plain language for those who don't nerd out on OSM. I especially like using snowplowing instead of winter service, since I think that will help minimize the temptation to report on current status. 

As for "current status" of plowing quality, to provide as an outlet for people who want to report on that, I looked into whether there might be any such suitable tag, but of course I did not find anything. Maybe the 'note' tag is most appropriate to collect this info (and to be sure it doesn't wind up getting collected in the wrong place)

**Comment by heatshear** [comment]
Actually, 'note' is probably a  bad idea... we'd then encourage this feedback, and get a lot of notes that most likely nobody will want to look at. Probably best just to trust the crowd to mostly declare accurately whether something is plowed or not, and to self-corrrect.

I don't know how nutty this would be to add, but maybe there's a widget (is that the right word?) that would let people vote on a way they have selected, in terms of how good it currently is for riding on. It would be an outlet for that desire to report, and over time, maybe it would be useful input to the type of map Alex is wanting to build one day... real conditions.

**Comment by zzptichka** [comment]
There is no easy way to setup voting.
Best we can do is use one of the secondary tags for `winter_service`, like `winter_service:quality` or something. So people can change it.

**Comment by heatshear** [comment]
That sounds perfect.

**Comment by matthewdarwin** [comment]
Voting would need to be tracked in a separate database.
