### ISSUE TITLE
winter map (others?) Mapillary open in new window

### ISSUE THREAD

**Issue by heatshear** [BikeOttawa/maps.bikeottawa.ca-frontend#15]
Playing with the winter map on iPad, it was easy to accidentally touch the image, which then took us to Mapillary, but in the same window. That was a problem generally, but especially when trying to edit the map. Mapillary should open in a new window. Same goes for any links (like to Bike Ottawa, facebook, twitter)... should open in a new window.

**Comment by zzptichka** [comment]
Done in https://github.com/BikeOttawa/maps.bikeottawa.ca-frontend/commit/55f70cebb2d2542cadb5cfd1c2cc2dc393bd5bd6
