### ISSUE TITLE
feature request: contraflow lanes

### ISSUE THREAD

**Issue by heatshear** [BikeOttawa/maps.bikeottawa.ca-frontend#22]
Typical painted on-street bike lanes will be a challenge to say whether they are plowed or not, so perhaps best not to show them at least for now, but I'd like to make an exception for physically protected lanes and contraflow lanes. Some of these are already included in the query, but others aren't, so here's as complete a list I could come up with that I think is actually present in city's map.

highway=cycleway (when they are mapped as a separate way)
cycleway=track (for tracks on either side of an undivided road)
cycleway:right=track (track on one side of the road only, whether or not bidirectional)
cycleway:left=track (track on one side of the road only, contraflow or bidirectional)
cycleway:left=opposite_lane (contraflow with no separation)

**Comment by heatshear** [comment]
Though now it occurs to me that, when these ways are mapped as part of the road, it won't be proper to tag them as winter_service=no... for that reason, they should be mapped as separate ways. So maybe this issue can just be closed.

**Comment by zzptichka** [comment]
- All cycle tracks are mapped as separate ways in Ottawa. If there are any I'm not aware of they need to be mapped as separate ways. 
- There are less than 10 contra flow lanes in Ottawa. We can easily tag them manually without adding more confusion to the map.

**Comment by heatshear** [comment]
yeah, I'm looking at one now on graham... tagging a painted contraflow lane on a oneway street is fine (cycleway:left=opposite_lane). It's how to tag whether or not it's plowed when that is different from the road that I can't figure out. The city should just do a good job of plowing them and save me the headache. But some aren't plowed.
