### ISSUE TITLE
Error / no data on maps.bikeottawa.ca/isochrones

### ISSUE THREAD

**Issue by tordans** [BikeOttawa/maps.bikeottawa.ca-frontend#25]
I get an error at https://maps.bikeottawa.ca/isochrones/?&lat=45.41759068790711&lng=-75.69501434011754&lts=lts4& for a few days now.

> Error
> Something went wrong. Either our server didn't respond or the request was blocked by your browser.
> Please refresh the page and contact Bike Ottawa if this error doesn't go away.

There is a cyclehack-weekend the comming weekend where I want to show how great those three maps are. It would be awesome, if you could get it back up until then :-).

Thanks for those great maps!

**Comment by tordans** [comment]
Those are the errors from the chrome browser console:

```
479 -75.69501434011754 45.41759068790711
?&lat=45.41759068790711&lng=-75.69501434011754&lts=lts4&:481 GET https://maps.bikeottawa.ca:3000/?lng=-75.69501434011754&lat=45.41759068790711&radius=3.5&deintersect=true&concavity=2&lengthThreshold=0&units=kilometers&cellSize=0.06&dir=lts4&intervals=3&intervals=6&intervals=9&intervals=12&intervals=15& 502 (Bad Gateway)
…

1 Access to fetch at 'https://maps.bikeottawa.ca:3000/?lng=-75.69501434011754&lat=45.41759068790711&radius=3.5&deintersect=true&concavity=2&lengthThreshold=0&units=kilometers&cellSize=0.06&dir=lts4&intervals=3&intervals=6&intervals=9&intervals=12&intervals=15&' from origin 'https://maps.bikeottawa.ca' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

494 TypeError: Failed to fetch
(anonymous) @ ?&lat=45.41759068790711&lng=-75.69501434011754&lts=lts4&:494
Promise.catch (async)
fetchIsochrones @ ?&lat=45.41759068790711&lng=-75.69501434011754&lts=lts4&:493
(anonymous) @ ?&lat=45.41759068790711&lng=-75.69501434011754&lts=lts4&:381
O.fire @ evented.js:115
O.fire @ evented.js:130
i._load @ style.js:260
(anonymous) @ style.js:196
r.onload @ ajax.js:89
load (async)
t.getJSON @ ajax.js:81
i.loadURL @ style.js:191
o.setStyle @ map.js:965
o @ map.js:382
(anonymous) @ ?&lat=45.41759068790711&lng=-75.69501434011754&lts=lts4&:131
```

**Comment by matthewdarwin** [comment]
How is it now?

**Comment by tordans** [comment]
@matthewdarwin I see results again, thanks a lot!

Quick question – not sure if its a bug or feature:

https://maps.bikeottawa.ca/isochrones/?&lat=45.40837206584541&lng=-75.73265109702034&lts=lts1& shows a small area.
But all lts2,3,4 show the _same_ area https://maps.bikeottawa.ca/isochrones/?&lat=45.40837206584541&lng=-75.73265109702034&lts=lts3&
To me it looks like there is only data for 1 and 4, maybe?

**Comment by matthewdarwin** [comment]
You picked a starting point that is very connected on LTS2, so changing LTS to LTS3 or LTS4 makes no difference.  Change the starting point and you will see different results.
