### ISSUE TITLE
Brand maps.bikeottawa.ca with logo etc

### ISSUE THREAD

**Issue by matthewdarwin** [BikeOttawa/maps.bikeottawa.ca-frontend#3]
The index.html file uses "OttBike" instead of "BikeOttawa".  Also it would be good to have the BikeOttawa logo.

**Comment by matthewdarwin** [comment]
This is a request from Hans.  I see index.html is checked in, so I am opening an issue for it.

**Comment by heatshear** [comment]
I'm giving up on adding a logo/link to each map. I won't be able to figure that out very easily. But I did upload our square logo to the images folder. It would be great if someone could put it on each map. The plan is to officially announce these Wednesday at 11 (when Shawn is presenting at the Ontario cycling summit)

**Comment by matthewdarwin** [comment]
I think this issue is resolved now.
